package appy_templates

import (
	"fmt"
	"time"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// Now returns the current time
func Now() time.Time {
	return time.Now()
}

// FormatTime formats a time.Time object to a string
func FormatTime(t time.Time) string {
	return t.Format("Mon Jan 2 15:04:05 MST 2006")
}

// Title converts a string to uppercase
func Title(s string) string {
	return cases.Title(language.AmericanEnglish).String(s)
}

func GeneratedNotice() string {
	return fmt.Sprintf("//\n// This is an auto generated file. Do not edit this file manually.\n// Generated at %v\n//", time.Now().Format("Mon Jan 2 15:04:05 MST 2006"))
}

func PartialGenerationStart() string {
	return fmt.Sprintln("// @@partial-generation-start")
}

func PartialGenerationEnd() string {
	return fmt.Sprintln("// @@partial-generation-end")
}

var funcMap = map[string]interface{}{
	"Now":                    Now,
	"FormatTime":             FormatTime,
	"Title":                  Title,
	"GeneratedNotice":        GeneratedNotice,
	"PartialGenerationStart": PartialGenerationStart,
	"PartialGenerationEnd":   PartialGenerationEnd,
}
